### ISSUE TITLE
Issue when attaching the Locallab map viewpager 2

### ISSUE THREAD

**Issue by rajeshjadidminc** [LocusLabsGit/Android-Docs-Sample-Code-SDK-3-Samples#1]
Application getting stuck when attaching fragment inside Viewpager 2 and whole application is freezing.

I have used the same code as you have provide on below link
https://android.maps.locuslabs.com/docs/fullscreen-map

**Comment by rajeshjadidminc** [comment]
Are there any updates on this showVenue() freezing the whole UI, or can we use any thread-safe method?

**Comment by LocusLabsGit** [comment]
Hi,

Please contact support@atrius.com with any support queries and include your account name. Note that using the map in a viewpager is not supported at this time.
